# Simple workflow for deploying static content to GitHub Pages
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: 'deploy'
  cancel-in-progress: true

env:
  PUBLIC_URL: https://aghents.github.io/lab-website

jobs:
  deploy:
    environment:
      name: GitHub Pages
      url: ${{ env.PUBLIC_URL }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Build
        run: |
          export PUBLIC_URL=${{ env.PUBLIC_URL }}
          yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          #github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
